baseURL = 'https://blog.aegides.be/'
languageCode = 'en-us'
title = 'Aegides Blog'

[pagination]
  pagerSize = 4


[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"